### ISSUE TITLE
Global Account not found by Terraform script

### ISSUE THREAD

**Issue by tim-sh** [SAP-samples/btp-genai-starter-kit#32] opened 2024-05-22 15:19 UTC
# Observation

The `run.sh` script throws an error stating that the Global Account is not found.

# Reproduction

1. Take all the steps listed in [Step 1: Setup SAP BTP infrastructure](https://github.com/SAP-samples/btp-genai-starter-kit?tab=readme-ov-file#step-1-setup-sap-btp-infrastructure).
2. Observe the following as part of the output (I abbreviated account IDs):
```
Setting up SAP BTP infrastructure
…
Terraform has been successfully initialized!
…
Applying terraform script
--------------------------------------------------------------------------------
/workspaces/btp-genai-starter-kit/scripts/step01_setup_infra
var.BTP_PASSWORD
  Your BTP password.

  Enter a value: <secret>
…
Terraform planned the following actions, but then encountered a problem:

  # random_id.subaccount_domain_suffix will be created
  + resource "random_id" "subaccount_domain_suffix" {
      + b64_std     = (known after apply)
      + b64_url     = (known after apply)
      + byte_length = 12
      + dec         = (known after apply)
      + hex         = (known after apply)
      + id          = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + globalaccount_id        = "cd…55"
  + subaccount_name         = "b9…8c"
  + subaccount_region       = "eu10"
  + timestamp_test_finished = (known after apply)
╷
│ Error: unableToCreateClient
│ 
│   with provider["registry.terraform.io/sap/btp"],
│   on provider.tf line 11, in provider "btp":
│   11: provider "btp" {
│ 
│ Global account 'cd…55' not found. Try again and make sure to provide the global account's subdomain. [Status:
│ 404; Correlation ID: 74b6d037-dd4a-d9a9-7a4e-d43f1cdd56e4]
╵
The 'terraform apply' command was not successful. Exiting.
```

# Remarks

- The Global Account subdomain used is listed in the Global-Account landing page in Cloud Cockpit.
- On my machine (i.e. outside the Docker container), `btp target --global-account cd…55` does succeed, confirming that the Global Account subdomain is valid.
- The same problem also occurs if the *name* (rather than ID, which was just a try) of the *subaccount* is used.
- Networking in the container does function.

**Comment by EvgeniiSkrebtcov** [comment] 2024-05-27 06:53
UPD: As idetified with the incident creator, the issue is not related to the live BTP landscape.

**Comment by rui1610** [comment] 2024-05-31 13:15
Give that this is not related to the BTP live landscape, I'm closing this issue. @tim-sh: please reach out to us via the SAP internal channels.

**Closed by rui1610** 2024-05-31 13:15 UTC
